# Standards: 1.2
---
- name: Remove legacy key
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    state: absent
  tags:
    - dotnet

- name: Remove legacy repo
  apt_repository:
    repo: "deb https://packages.microsoft.com/{{ dotnet_repo_distribution }}/{{ dotnet_repo_version }}/prod {{ dotnet_repo_release }} main"
    filename: microsoft
    update_cache: False
    state: absent
  tags:
    - dotnet

- name: Download repo key
  shell:
    cmd: "curl -sSL 'https://packages.microsoft.com/keys/microsoft.asc' | gpg --dearmor --output {{ dotnet_keyring }}"
    creates: "{{ dotnet_keyring }}"
  tags:
    - dotnet

- name: Add apt repository
  apt_repository:
    repo: "deb [signed-by={{ dotnet_keyring }}] https://packages.microsoft.com/{{ dotnet_repo_distribution }}/{{ dotnet_repo_version }}/prod {{ dotnet_repo_release }} main"
    filename: microsoft
    update_cache: True
    state: present
  tags:
    - dotnet

- name: Enforce libicu package
  when: dotnet_repo_release | default('') == 'bionic'
  apt:
    deb: http://mirrors.edge.kernel.org/ubuntu/pool/main/i/icu/libicu63_63.2-2_amd64.deb
    state: present
  tags:
    - dotnet

- name: Install required packages
  loop: "{{ dotnet_packages }}"
  package:
    name: "{{ item }}"
    state: present
  tags:
    - dotnet

...
